apiVersion: install.istio.io/v1alpha1
metadata:
 name: istio-controlplane
 namespace: istio-system
kind: IstioOperator
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            type: NodePort
            ports:
              - name: status-port
                port: 15021
              - name: tls-istiod
                port: 15012
              - name: tls
                port: 15443
                nodePort: 31371
              - name: http2
                port: 80
                nodePort: 31381
                targetPort: 8280
              - name: https
                port: 443
                nodePort: 31391
                targetPort: 8243
  values:
    global:
      # Multi-cluster properties
      meshID: {{ include "mesh.id" . }}
      multiCluster:
        clusterName: {{ .Values.global.clusterName }}
      network: {{ include "network.name" . }}
